export const egfOption = {

  // HEADERS
  messageKey: 'm',
  emptyMessage: 'Aucune données',
  userKey: 'u',
  currentUserKey: 'scu',
  tokenKey: 'auth_token',
  userRolesKey: 'r',
  urlKey: 'to',
  // OTHER OPTIONS
  SPACE: ' ',
  EMPTY: '',
  uploadFileNameSeparator: ';',
  printTitle: 'Imprimer',
  addTitle: 'Ajouter',
  editTitle: 'Modifier',
  deleteTitle: 'Supprimer',
  saveTitle: 'Enregistrer',
  cancelTitle: 'Annuler',
  validTitle: 'Valider',
  detailsTitle: 'Plus d\'informations',
  uploadTitle: 'Charger',
  returnTitle: 'Retour',
  confirmationTitle: 'Oui',
  nonConfirmationTitle: 'Non',
  closeConfirmationTitle: 'Fermer',
  actionTitle: 'Actions',
  refreshTitle: 'Rafraichir',
  // MESSAGE OPTIONS
  authenticationFailedMessage: 'Nom d\'utilisateur ou mot de passe incorrect !',
  authenticationInactifMessage: 'Votre compte a été  desactivé, contacter l\'admin système !',
  notAuthorizedMessage: 'Vous n\'êtes pas authorisés à accèder à cette page',
  expiredConnexionMessage: 'La connexion a expirée, réconnectez vous pour continuer',
  requiredMessage: 'Vous devez renseigner une valeur',
  invalidEmailMessage: 'Adresse email invalide',
  emptyTableMessage: 'Aucune donnée dans la table',
  emptyDropdownMessage: 'Aucune donnée correspondante',
  deleteConfirmationMessage: 'Etes-vous sûr de vouloir supprimer cet élément ?',
  deleteConfirmationTitle: 'Suppression de l\'élément',
  uploadFileTitle: 'Chargement des pièces jointes',
  selectFileTitle: 'Selectionner le fichier',
  imageTitle: 'Image associee',
  noImageTitle: 'Aucune image associee',
  noFileTitle: 'Aucun fichier associe !',
  suspendTitle: 'Suspendre',
  reactivateTitle: 'Réactiver',
  transferTitle: 'Transférer',
  alternativeMessage: 'Problème de connexion, verifiez que le serveur est en marche',
  dvEmptyMessage: 'Aucun element trouvé',
  errorMessage: 'L\'opération n\'a pas été effectuée avec succès!',
  successMessage: 'Opération éffectuée avec succès!',
  listColor: [
    {key: '0', color: '#0B60A9'},
    {key: '1', color: '#ef9b0f'},
    {key: '2', color: '#dc3545'},
    {key: '3', color: '#34A835'},
    {key: '4', color: '#798892'},
    {key: '5', color: '#7f3ddb'},
    {key: '6', color: '#17a2b8'},
  ],
};
