
export const environment = {
  production: false,
  firebaseConfig:{
    apiKey: "AIzaSyBN3102nuBfkCvXRdKfCl3M3Qeq3WpJgOw",
    authDomain: "egfmali.firebaseapp.com",
    databaseURL: "https://egfmali.firebaseio.com",
    projectId: "egfmali",
    storageBucket: "egfmali.appspot.com",
    messagingSenderId: "1029078377931",
    appId: "1:1029078377931:web:bad04de3c4d05120fa024e",
    measurementId: "G-74PRMZNCNW"
  },


  googleMaps: {
    apiKey: 'AIzaSyBSvo0x8v3C6aFWcSi2zooOC9tqGCOqCj4',
    libraries: ['places']
  },

  PaymentMethod : ["CASH","ORANGE MONEY","MOBI CASH","VISA","PAY PAL","MASTER CARD"],

  PayementMode : ["INTEGRAL","TRANCHE",],

  PayementType : ["ESPECE","CHEQUE","VIREMENT",],


  pays :[
    // A
    {name: "Afghanistan",value:""},
    {name: "Afrique du Sud",value:""},
    {name: "Albanie",value:""},
    {name: "Algérie",value:""},
    {name: "Allemagne",value:""},
    {name: "Andorre",value:""},
    {name: "Angola",value:""},
    {name: "Antigua et Barbuda",value:""},
    {name: "Arabie saoudite",value:""},
    {name: "Argentine",value:""},
    {name: "Arménie",value:""},
    {name: "Australie",value:""},
    {name: "Autriche",value:""},
    {name: "Azerbaïdjan",value:""},
    {name: "Bahamas",value:""},
    {name: "Bahrein",value:""},
    {name: "Bangladesh",value:""},
    {name: "Barbade",value:""},
    {name: "Belgique",value:""},
    {name: "Bélize",value:""},
    {name: "Benin",value:""},
    {name: "Bhoutan",value:""},
    {name: "Biélorussie",value:""},
    {name: "Bolivie",value:""},
    {name: "Bosnie-Herzégovine",value:""},
    {name: "Botswana",value:""},
    {name: "Brésil",value:""},
    {name: "Brunei",value:""},
    {name: "Bulgarie",value:""},
    {name: "Burkina Faso",value:""},
    {name: "Burundi",value:""},
    {name:  "Cambodge",value:""},
    {name: "Cameroun",value:""},
    {name: "Canada",value:"ca"},
    {name: "Cap Vert",value:""},
    {name: "Centrafrique",value:""},
    {name: "Chili",value:""},
    {name: "Chine",value:""},
    {name: "Chypre",value:""},
    {name: "Colombie",value:""},
    {name: "Comores",value:""},
    {name: "Congo démocratique",value:""},
    {name: "Congo",value:""},
    {name: "Corée du Nord",value:""},
    {name: "Corée du Sud",value:""},
    {name: "Costa Rica",value:""},
    {name: "Côte d'Ivoire",value:""},
    {name: "Croatie",value:""},
    {name: "Cuba",value:""},
    {name: "Danemark",value:""},
    {name: "Djibouti",value:""},
    {name: "Dominique",value:""},
    {name: "RépubliqueDominicaine",value:""},
    {name: "Egypte",value:""},
    {name: "Emirats Arabes Unis",value:""},
    {name: "Equateur",value:""},
    {name: "Erythrée",value:""},
    {name: "Espagne",value:""},
    {name: "Estonie",value:""},
    {name: "Etats-Unis",value:"us"},
    {name: "Ethiopie",value:""},
    {name:  "Fidji",value:""},
    {name: "Finlande",value:""},
    {name: "France",value:"fr"},
    {name:"Gabon",value:""},
    {name: "Gambie",value:""},
    {name: "Géorgie",value:""},
    {name: "Ghana",value:""},
    {name: "Grèce",value:""},
    {name: "Grenade",value:""},
    {name: "Groenland",value:""},
    {name: "Guatémala",value:""},
    {name: "Guinée",value:""},
    {name: "Guinée Bissau",value:""},
    {name: "Guinée équatoriale",value:""},
    {name: "Guyana",value:""},
    {name: "Haïti",value:""},
    {name: "Honduras",value:""},
    {name: "Hong Kong",value:""},
    {name: "Hongrie",value:""},
    {name: "Inde",value:""},
    {name: "Indonésie",value:""},
    {name: "Irak",value:""},
    {name: "Iran",value:""},
    {name: "Irlande",value:""},
    {name: "Islande",value:""},
    {name: "Israël",value:""},
    {name: "Italie",value:""},
    {name: "Jamaïque",value:""},
    {name: "Japon",value:""},
    {name: "Jordanie",value:""},
    {name: "Kazakhstan",value:""},
    {name: "Kenya",value:""},
    {name: "Kirghizstan",value:""},
    {name: "Kiribati",value:""},
    {name: "Koweït",value:""},
    {name:  "Laos",value:""},
    {name: "Lesotho",value:""},
    {name: "Lettonie",value:""},
    {name: "Liban",value:""},
    {name: "Liberia",value:""},
    {name: "Libye",value:""},
    {name: "Liechtenstein",value:""},
    {name: "Lituanie",value:""},
    {name: "Luxembourg",value:""},
    {name:  "Macédoine",value:""},
    {name: "Madagascar",value:""},
    {name: "Malaisie",value:""},
    {name: "Malawi",value:""},
    {name: "Maldives",value:""},
    {name: "Mali",value:"ml"},
    {name: "Malte",value:""},
    {name: "Maroc",value:""},
    {name: "Marshall",value:""},
    {name: "Maurice",value:""},
    {name: "Mauritanie",value:""},
    {name: "Mexique",value:""},
    {name: "Micronésie",value:""},
    {name: "Moldavie",value:""},
    {name: "Monaco",value:""},
    {name: "Mongolie",value:""},
    {name: "Mozambique",value:""},
    {name: "Myanmar",value:""},
    {name: "Namibie",value:""},
    {name: "Népal",value:""},
    {name: "Nicaragua",value:""},
    {name: "Niger",value:""},
    {name: "Nigeria",value:""},
    {name: "Norvège",value:""},
    {name: "Nouvelle Zélande",value:""},
    {name:  "Oman",value:""},
    {name: "Ouganda",value:""},
    {name: "Ouzbekistan",value:""},
    {name: "Pakistan",value:""},
    {name: "Palau",value:""},
    {name: "Palestine",value:""},
    {name: "Panama",value:""},
    {name: "Papouasie - Nouvelle Guinée",value:""},
    {name: "Paraguay",value:""},
    {name: "Pays-Bas",value:""},
    {name: "Pérou",value:""},
    {name: "Philippines",value:""},
    {name: "Pologne",value:""},
    {name: "Porto Rico",value:""},
    {name: "Portugal",value:""},
    {name: "Qatar",value:""},
    {name: "Roumanie",value:""},
    {name: "Royaume-Uni",value:""},
    {name: "Russie",value:""},
    {name: "Rwanda",value:""},
    {name: "Saint Christophe et Nevis",value:""},
    {name: "Saint Vincent et les Grenadines",value:""},
    {name: "Sainte Lucie",value:""},
    {name: "Salomon",value:""},
    {name: "Salvador",value:""},
    {name: "Samoa",value:""},
    {name: "São Tomé et Príncipe",value:""},
    {name: "Sénégal",value:"sn"},
    {name: "Seychelles",value:""},
    {name: "Sierra Leone",value:""},
    {name: "Singapour",value:""},
    {name: "Slovaquie",value:""},
    {name: "Slovénie",value:""},
    {name: "Somalie",value:""},
    {name: "Somaliland",value:""},
    {name: "Soudan",value:""},
    {name: "Sri Lanka",value:""},
    {name: "Suède",value:""},
    {name: "Suisse",value:""},
    {name: "Surinam",value:""},
    {name: "Syrie",value:""},
    {name: "Swaziland",value:""},
    {name: "Tadjikistan",value:""},
    {name: "Taïwan",value:""},
    {name: "Tanzanie",value:""},
    {name: "Tchad",value:""},
    {name: "Tchéquie",value:""},
    {name: "Thaïlande",value:""},
    {name: "Tibet",value:""},
    {name: "Timor Oriental",value:""},
    {name: "Togo",value:""},
    {name: "Tonga",value:""},
    {name: "Trinité et Tobago",value:""},
    {name: "Tunisie",value:""},
    {name: "Turkmenistan",value:""},
    {name: "Turquie",value:""},
    {name: "Tuvalu",value:""},
    {name: "Ukraine"},
    {name: "Uruguay",value:""},
    {name: "Vanuatu",value:""},
    {name: "Vatican",value:""},
    {name: "Vénézuéla",value:""},
    {name: "Vietnam",value:""},
    {name: "Yémen",value:""},
    {name: "Yougoslavie",value:""},
    {name: "Zambie",value:""},
    {name: "Zimbabwe"}
  ],

  roles: [

    {"name": "DASHBOARD", "description": "Voir le tableau de bord"},

    {"name": "USERS", "description": "Voir les utilisateurs"},
    {"name": "USER_ADD", "description": "Ajouter un utilisateur"},
    {"name": "USER_EDITE", "description": "Modifier un utilisateur"},
    {"name": "USER_DELETE", "description": "Supprimer un utilisateur"},

    {"name": "PROFILS", "description": "Voir les profils"},
    {"name": "PROFIL_ADD", "description": "Ajouter un profil"},
    {"name": "PROFIL_EDITE", "description": "Modifier un profil"},
    {"name": "PROFIL_DELETE", "description": "Supprimer un profil"},

    {"name": "PROFIL_ROLES", "description": "Affectation des aules a un profil"},

    {"name": "ROLES", "description": "Voir les roles"},

    {"name": "CONFIGURATION", "description": "Configurer l'application"},

    {"name": "TYPES_DEVIS", "description": "Voir les type de devis"},
    {"name": "TYPE_DEVIS_ADD", "description": "Ajouter un type de devis"},
    {"name": "TYPE_DEVIS_EDITE", "description": "Modifier un type de devis"},
    {"name": "TYPE_DEVIS_DELETE", "description": "Supprimer un type de devis"},

    {"name": "TYPES_COLIS", "description": "Voir les type de colis"},
    {"name": "TYPE_COLIS_ADD", "description": "Ajouter un type de colis"},
    {"name": "TYPE_COLIS_EDITE", "description": "Modifier un type de colis"},
    {"name": "TYPE_COLIS_DELETE", "description": "Supprimer un type de colis"},

    {"name": "NATURES_COLIS", "description": "Voir les natures de colis"},
    {"name": "NATURE_COLIS_ADD", "description": "Ajouter une nature de colis"},
    {"name": "NATURE_COLIS_EDITE", "description": "Modifier une nature de colis"},
    {"name": "NATURE_COLIS_DELETE", "description": "Supprimer une nature de colis"},

    {"name": "VIELLE_ESCALES", "description": "Voir les villes d'escales"},
    {"name": "VIELLE_ESCALE_ADD", "description": "Ajouter une ville d'escale"},
    {"name": "VIELLE_ESCALE_EDITE", "description": "Modifier une ville d'escale"},
    {"name": "VIELLE_ESCALE_DELETE", "description": "Supprimer une ville d'escale"},

    {"name": "POINT_DEPOTS", "description": "Voir les points de depot"},
    {"name": "POINT_DEPOT_ADD", "description": "Ajouter un point de depot"},
    {"name": "POINT_DEPOT_EDITE", "description": "Modifier un point de depot"},
    {"name": "POINT_DEPOT_DELETE", "description": "Supprimer un point de depot"},

    {"name": "TYPE_ACHEMINEMENTS", "description": "Voir les types d'achéminementss"},
    {"name": "TYPE_ACHEMINEMENT_ADD", "description": "Ajouter un type d'achéminement"},
    {"name": "TYPE_ACHEMINEMENT_EDITE", "description": "Modifier un type d'achéminement"},
    {"name": "TYPE_ACHEMINEMENT_DELETE", "description": "Supprimer un type d'achéminement"},

    {"name": "SOCIETES", "description": "Voir les societés"},
    {"name": "SOCIETE_ADD", "description": "Ajouter une societé"},
    {"name": "SOCIETE_EDITE", "description": "Modifier une societé"},
    {"name": "SOCIETE_DELETE", "description": "Supprimer une societé"},

    {"name": "TRAJETS", "description": "Voir les trajets"},
    {"name": "TRAJET_ADD", "description": "Ajouter un trajet"},
    {"name": "TRAJET_EDITE", "description": "Modifier un trajet"},
    {"name": "TRAJET_DELETE", "description": "Supprimer un trajet"},

  ]


};
